### PR TITLE
I18n support and first russian translation

### PR DESCRIPTION
**Pull request by vlad20012**
How it works:
Lang file is JSON file stored in lang dir. All langs except EN is
optional. From JS we requesting both en.json and user lang and
then merging their. Thus, if user language or some property not
defined, EN used. Translation can be performed by specifying
html attribute "data-lang" or directly from JS. Language name
is currently retrieving from window.navigator only

### CODE REVIEW

**Comment by HelloZeroNet** [comment]
Thanks for the effort it looks good, but i have thought about it a bit and came up with this idea:

A plugin (can be enabled by default) that is allows you find replace part of source code based on .json language files. So it would not require any modification in the current site's source code, but if you create a all.js.lang_ru.json file and the client's browser is russian (or changed to russian language using the webui) then it would return a translated all.js for the browser. Example for all.js.lang_ru.json:
```json
{
 "Newest topics": "Последние темы",
 "Follow in Newsfeed": "Подписаться",
 "#{topic.comments_num} comment": "#{topic.comments_num} комментариев"
}
```
This would be better because:
 - No need to replace texts with variables (faster, more readable, easier to develop)
 - Does not need extra `fileGet` on every page request
 - Allows to change word order

throughts?

**Comment by vlad20012** [comment]
First I want to say that I definitely support the centralized, ZeroNet-provided i18n. But plain string replacement has a large number of drawbacks and IMHO will complicate the development of a much more than key-based translation.
1. Don't forget about typos and spelling. With key-based translation it is not a problem, but your method will cause all langs modification, and easy to forget to do it
1. File-based replacement does not include an option when one string used in muliple files (html, js, css)
1. Possible that some translatable string become a keyword like JQuery selector in some places
1. It is too hard to start initial translation to new laguage without referenced EN lang file. All other language may be incomplete at some time.
1. Replace something like "#{topic.comments_num}" is so horrible as possible =D. First, it is CoffeeScript, but you replacing all.js. Then, var names should be easy to change and lang files should never depends on it.

I can offer the following solution:
First we defining function like this
```
LTL = key... -> key[0]
```
Then we using this to perform translation
```
LTL("topic_tpl.comments_num", topic.comments_num)
```
Or (for development needs)
```
LTL("%s comment", topic.comments_num)
```
This line in CoffeScript will expanded to predictable JS code. Then this pattern may be analyzed from python and replaced to normal string concatenation. And I believe that the proposed key-based lang files are good enough.

**Comment by HelloZeroNet** [comment]
Typos/variable changes are rare, the worst that can happen is turning some text back to english, then the translation maintainer able to adjust it easily.
Html/css translation could be also possible in the same way (index.html.lang_ru.json), text are rarely shared, but if this is a problem, then we can create a global translation/ru.json instead of per-file one.
From more bloated site source code vs bit harder to create the first translation i would choose the second.
I will try to do a hungarian translation for zerotalk to see if the name conflict is a real, unsolvable problem.

**Comment by vlad20012** [comment]
I think it is always better to use a single lang file, even if replacements is file-separated.
```
"all.js": {
    "": ""
},
"some other file": {...}
```

**Pull request closed without merging**
