### PR TITLE
Support more KxoID usernames

### PR DESCRIPTION
**Pull request by imachug**
Allow 2nd level KxoID registrars.

### CODE REVIEW

**Comment by imachug** [comment]
@HelloZeroNet Could you please take a look at this?

**Comment by filips123** [comment]
@imachug Can KxoID support also be added to other official ZeroNet sites?

**Comment by imachug** [comment]
Let's ask @HelloZeroNet about that.

**Comment by HelloZeroNet** [comment]
Why is the new public address necessary?

**Comment by imachug** [comment]
KxoID has two registrar levels. There are superadmins (level 1) who are actually KxoID developers, like me and Krixano, and there are admins (level 2), these are just some trusted peers who can only register usernames (a few were added recently). This PR adds level-2 support.

**Comment by krixano** [comment]
@HelloZeroNet 
image

Because the Trusted Peers only use level-2 (basically, they just sign registrations with a different key), a zite can easily select or change whether users registered by these Trusted Peers are allowed to login with the zite. This is in case there's any "Traitor Peer" who is a peer that has registered a non-unique username.

**Comment by imachug** [comment]
By the way, there will always be a list of all accepted and pending trusted peers on KxoID homepage.

**Comment by HelloZeroNet** [comment]
Ok, Thanks for the info!

**Pull request merged**
