### PR TITLE
Use date of vote instead of a 'one'

### PR DESCRIPTION
**Pull request by imachug**
Hello. Currently, topic URIs, comment URIs and basically everything else on most default sites contain date. However, I've just noticed that a plain "1" digit is used for votes, like this:

```json
  ...
  "8_12zcNM3BD6QwkonPrnCdbWBnGzu9b1rQRA": 1,
  ...
```

That doesn't sound like a good idea to me. One of the reasons is that using "1" makes mirroring ZeroTalk threads to other services more difficult: namely, it's not enough to just check a part of upvotes posted after a specific time. This is troublesome in messengers like Matrix: it allows getting *n* latest events (i.e. messages/upvotes/etc.), so without this PR merged, I'd have to load *all* events just to find what upvotes were counted and what weren't. On the other side, this PR won't affect UI/UX but will make mirroring easier.

### CODE REVIEW

**Comment by blurHY** [comment]
@shortcutme @HelloZeroNet

**Comment by imachug** [comment]
@HelloZeroNet What do you think about this?

**Comment by imachug** [comment]
@HelloZeroNet This PR blocks release of my project. Can you please merge it?

**Comment by blurHY** [comment]
As you see, huh.

**Comment by imachug** [comment]
Yay, thanks,

**Pull request merged**
